"""initial schema

Revision ID: 15d75828f74b
Revises: 
Create Date: 2026-08-10 19:48:22.204460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15d75828f74b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('public_code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('submission_paused', sa.Boolean(), nullable=False),
    sa.Column('slow_mode_seconds', sa.Integer(), nullable=False),
    sa.Column('danmaku_color_mode', sa.String(length=16), nullable=False),
    sa.Column('danmaku_default_color', sa.String(length=16), nullable=False),
    sa.Column('allow_custom_color', sa.Boolean(), nullable=False),
    sa.Column('auto_moderation_enabled', sa.Boolean(), nullable=False),
    sa.Column('overlay_font_size', sa.Integer(), nullable=False),
    sa.Column('overlay_speed', sa.Integer(), nullable=False),
    sa.Column('overlay_opacity', sa.Float(), nullable=False),
    sa.Column('overlay_font', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_public_code'), 'activities', ['public_code'], unique=True)
    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_activity_id'), 'events', ['activity_id'], unique=False)
    op.create_table('participants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('nickname', sa.String(length=24), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participants_activity_id'), 'participants', ['activity_id'], unique=False)
    op.create_index(op.f('ix_participants_token'), 'participants', ['token'], unique=True)
    op.create_table('danmaku',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.String(length=120), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'idempotency_key', name='uq_danmaku_activity_idempotency')
    )
    op.create_index(op.f('ix_danmaku_activity_id'), 'danmaku', ['activity_id'], unique=False)
    op.create_index(op.f('ix_danmaku_status'), 'danmaku', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_danmaku_status'), table_name='danmaku')
    op.drop_index(op.f('ix_danmaku_activity_id'), table_name='danmaku')
    op.drop_table('danmaku')
    op.drop_index(op.f('ix_participants_token'), table_name='participants')
    op.drop_index(op.f('ix_participants_activity_id'), table_name='participants')
    op.drop_table('participants')
    op.drop_index(op.f('ix_events_activity_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_table('admins')
    op.drop_index(op.f('ix_activities_public_code'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
