"""danmaku logs and bans

Revision ID: 260ebf827bfd
Revises: 15d75828f74b
Create Date: 2026-08-10 20:24:06.172236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '260ebf827bfd'
down_revision: Union[str, None] = '15d75828f74b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('target_value', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=True),
    sa.Column('banned_by', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bans_activity_id'), 'bans', ['activity_id'], unique=False)
    op.add_column('danmaku', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('danmaku', sa.Column('device_fingerprint', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('danmaku', 'device_fingerprint')
    op.drop_column('danmaku', 'ip_address')
    op.drop_index(op.f('ix_bans_activity_id'), table_name='bans')
    op.drop_table('bans')
    # ### end Alembic commands ###
