"""screen key plain

Revision ID: 4b908a6facbf
Revises: aaba5bef870a
Create Date: 2026-08-11 23:04:42.066523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b908a6facbf'
down_revision: Union[str, None] = 'aaba5bef870a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screen_keys', sa.Column('key_plain', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screen_keys', 'key_plain')
    # ### end Alembic commands ###
