"""screen key device flow

Revision ID: aaba5bef870a
Revises: ccf9b55e7069
Create Date: 2026-08-11 22:54:32.656774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaba5bef870a'
down_revision: Union[str, None] = 'ccf9b55e7069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite 不支持 ALTER COLUMN DROP NOT NULL，用 batch_alter_table 重建表
    with op.batch_alter_table('screen_keys') as batch_op:
        batch_op.add_column(sa.Column('device_id', sa.String(length=64), nullable=True))
        batch_op.alter_column('key_hash',
                   existing_type=sa.VARCHAR(length=64),
                   nullable=True)
        batch_op.create_index(op.f('ix_screen_keys_device_id'), ['device_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screen_keys') as batch_op:
        batch_op.drop_index(op.f('ix_screen_keys_device_id'))
        batch_op.alter_column('key_hash',
                   existing_type=sa.VARCHAR(length=64),
                   nullable=False)
        batch_op.drop_column('device_id')
    # ### end Alembic commands ###
