"""allow multiline danmaku config

Revision ID: ac10230e0480
Revises: 260ebf827bfd
Create Date: 2026-08-10 23:01:47.404694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac10230e0480'
down_revision: Union[str, None] = '260ebf827bfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('allow_multiline', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'allow_multiline')
    # ### end Alembic commands ###
